---
- name: BE SURE HOSTS FILE COLLECT
  template: src=hosts.j2 dest=/etc/hosts backup=yes

- name: START MYSQLD
  service: name=mysqld state=started enabled=yes

- name: COPY HTTPD.CONF
  template: src=httpd.conf dest=/etc/httpd/conf/httpd.conf backup=yes

- name: CPOY SSL DIRECTORY
  file: path=/usr/local/etc/ssl state=directory owner=root group=root mode=0755

- name: CPOY SSL CRT FILE
  copy: src=VAGRANT.crt dest=/usr/local/etc/ssl/VAGRANT.crt owner=root group=root mode=0644

- name: CPOY SSL CSR FILE
  copy: src=VAGRANT.csr dest=/usr/local/etc/ssl/VAGRANT.csr owner=root group=root mode=0644

- name: CPOY SSL KEY FILE
  copy: src=VAGRANT.key dest=/usr/local/etc/ssl/VAGRANT.key owner=root group=root mode=0644

- name: START HTTPD
  service: name=httpd state=restarted enabled=yes
