#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

require_once __DIR__ . '/Environment.php';

$envConf = \app\Environment::get();

defined('YII_DEBUG') or define('YII_DEBUG', isset($envConf['mode']) ? in_array($envConf['mode'], ['dev']) : true);
defined('YII_ENV') or define('YII_ENV', isset($envConf['mode']) ? $envConf['mode'] : 'dev');

require(__DIR__ . '/../vendor/autoload.php');
require(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
